DROP TABLE IF EXISTS tags;
DROP TABLE IF EXISTS comments;
DROP TABLE IF EXISTS badges;
DROP TABLE IF EXISTS votes;
DROP TABLE IF EXISTS post_links;
DROP TABLE IF EXISTS post_history;
DROP TABLE IF EXISTS posts;
DROP TABLE IF EXISTS users;
